kind: pipeline
type: docker
name: master
steps:
  - name: restore-cache
    image: meltwater/drone-cache
    settings:
      backend: filesystem
      restore: true
      cache_key: node_modules-taskvue
      archive_format: gzip
      filesystem_cache_root: "/var/lib/cache"
      mount:
        - node_modules
    volumes:
      - name: cache
        path: "/var/lib/cache"
  # Do stuff..
  - name: install
    image: node:14
    commands:
      - yarn install
  - name: rebuild-cache
    image: meltwater/drone-cache
    settings:
      backend: filesystem
      rebuild: true
      cache_key: node_modules-taskvue
      archive_format: gzip
      filesystem_cache_root: "/var/lib/cache"
      mount:
        - 'node_modules'
    volumes:
      - name: cache
        path: "/var/lib/cache"
  # Do stuff..
  - name: build
    image: node:14
    commands:
      - yarn run build
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host: 42.192.165.163
      username:
        from_secret: pro_user
      password:
        from_secret: pro_pass
      port: 22
      target: /data/docker/wwwroot/www.testmanage.szfba.cn
      source: dist/*
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: 42.192.165.163
      username:
        from_secret: pro_user
      password:
        from_secret: pro_pass
      port: 22
      script:
        - cd /data/docker/wwwroot/www.testmanage.szfba.cn
        - chown -R www.www dist
        - \cp -rf dist/* ./
        - rm -rf dist
volumes:
  - name: cache
    host:
      path: "/tmp/cache"
trigger:
  branch:
    - master
  event:
    - push
    - merge
